title: Ant Grasp Dataset
logo:
tagline: 'A video dataset of ant grasping'
description: A detailed instruction set to access a video dataset of Messor Barbarus ants grasping objects at 100 FPS.
google_analytics:
remote_theme: fongandrew/hydeout
paginate: 3
baseurl: '/ant-grasp-dataset'
author:
  name: Persie Rolley-Parnell
  url: https://prolley-parnell.github.io

plugins:
  - jekyll-paginate


exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post
