title: Ant Grasp Dataset
logo:
description: A detailed instruction set to access a video dataset of Messor Barbarus ants grasping objects at 100 FPS.
google_analytics:
remote_theme: fongandrew/hydeout
